reviewers:
  # The default reviewers
  defaults:
    - team:main # GitHub team

groups:
    a-main:
      - 2000arion # username
      - entcheneric # username

files:
  # Keys are glob expressions.
  # You can assign groups defined above as well as GitHub usernames.
  '.github/**':
    - a-main # group

options:
  ignore_draft: true
  enable_group_assignment: true

  # Randomly pick reviewers up to this number.
  # Do not set this option if you'd like to assign all matching reviewers.
  number_of_reviewers: 1

  # If it's true, the last matching files-change pattern takes the most precedence (CODEOWNERS-compatible)
  # See https://github.com/necojackarc/auto-request-review/pull/80 for more details.
  last_files_match_only: false
