name: 'Close inactive issues and pull requests'
permissions:
  issues: write
  pull-requests: write

on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9.0.0
        with:
          stale-pr-message: 'This pull request has been marked as inactive because it has been open for 30 days and has no activity. Remove the "stale" label or this comment, otherwise this pull request will be closed in 5 days.'
          close-pr-message: 'This pull request has been closed because it has had no activity for 5 days.'
          stale-issue-message: 'This issue has been marked as inactive because it has been open for 30 days and has no activity. Remove the "stale" label or this comment, otherwise this issue will be closed in 5 days.'
          close-issue-message: 'This issue has been closed because it has had no activity for 5 days.'
          days-before-stale: 30
          days-before-close: 5
          exempt-issue-labels: ''
          exempt-pr-labels: 'help wanted'
          exempt-all-milestones: true
          operations-per-run: 100
          stale-issue-label: 'stale'
